In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data= pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
y=data.iloc[:,13]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [20]:
X=data.iloc[:,3:13]
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [23]:
geo= pd.get_dummies(X['Geography'],drop_first=True)
geo

      Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [25]:
gender= pd.get_dummies(X['Gender'],drop_first=True)
gender

      Male
0        0
1        0
2        0
3        0
4        0
...    ...
9995     1
9996     1
9997     0
9998     1
9999     0

[10000 rows x 1 columns]

In [26]:
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [31]:
#X.drop(['Gender','Geography'],inplace=True,axis=1)
X=pd.concat([X,geo,gender],axis=1)
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [33]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [35]:
X_train = sc.fit_transform(X_train)
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [36]:
X_test = sc.fit_transform(X_test)

In [37]:
import keras

ModuleNotFoundError: No module named 'keras'

In [38]:
!pip install keras

Collecting keras
  Obtaining dependency information for keras from https://files.pythonhosted.org/packages/fe/58/34d4d8f1aa11120c2d36d7ad27d0526164b1a8ae45990a2fede31d0e59bf/keras-2.14.0-py3-none-any.whl.metadata
  Downloading keras-2.14.0-py3-none-any.whl.metadata (2.4 kB)
Downloading keras-2.14.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.1 MB/s eta 0:00:0000:010:01
Installing collected packages: keras
Successfully installed keras-2.14.0

In [40]:
!pip install tensorflow

Collecting tensorflow
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/d6/69/d461fa09235326e08b7ca463d5491426fdd4908ef6d3f9ed51d0777dc071/tensorflow-2.13.0-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Downloading tensorflow-2.13.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (2.6 kB)
Collecting tensorflow-macos==2.13.0 (from tensorflow)
  Obtaining dependency information for tensorflow-macos==2.13.0 from https://files.pythonhosted.org/packages/f1/cc/6c262ae6f3a23b118b1104fa5f6126067744ffa9226faade202b0a20bdd3/tensorflow_macos-2.13.0-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Downloading tensorflow_macos-2.13.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (3.2 kB)
Collecting absl-py>=1.0.0 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 2.6 MB/s eta 0:00:00a 0:00:01
Collecting astunparse>=1.6.0 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.1.21 (from tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for flatbuffers>=23.1.21 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Downloading flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
Collecting gast<=0.4.0,>=0.2.1 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting google-pasta>=0.1.1 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 5.2 MB/s eta 0:00:00
Requirement already satisfied: h5py>=2.9.0 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.13.0->tensorflow) (3.7.0)
Collecting libclang>=13.0.0 (from tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for libclang>=13.0.0 from https://files.pythonhosted.org/packages/32/1f/981809b77b71972beec34b3ff5422c1b1f7e519daac7b3cbd055c05ba2cf/libclang-16.0.6-py2.py3-none-macosx_11_0_arm64.whl.metadata
  Downloading libclang-16.0.6-py2.py3-none-macosx_11_0_arm64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy<=1.24.3,>=1.22 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.13.0->tensorflow) (1.24.3)
Collecting opt-einsum>=2.3.2 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: packaging in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.13.0->tensorflow) (23.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 from https://files.pythonhosted.org/packages/fe/f3/957db80e5b9f7fd7df97e5554fdc57919dfad24e89291223fd04a0e3c84f/protobuf-4.24.3-cp37-abi3-macosx_10_9_universal2.whl.metadata
  Downloading protobuf-4.24.3-cp37-abi3-macosx_10_9_universal2.whl.metadata (540 bytes)
Requirement already satisfied: setuptools in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.13.0->tensorflow) (68.0.0)
Requirement already satisfied: six>=1.12.0 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.13.0->tensorflow) (1.16.0)
Collecting termcolor>=1.1.0 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Requirement already satisfied: wrapt>=1.11.0 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorflow-macos==2.13.0->tensorflow) (1.14.1)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for grpcio<2.0,>=1.24.3 from https://files.pythonhosted.org/packages/a1/9c/ef89aae6948949a891a50e19bb951aac2f7ceb9561fdfdcd07c9b890ed6c/grpcio-1.58.0-cp311-cp311-macosx_10_10_universal2.whl.metadata
  Downloading grpcio-1.58.0-cp311-cp311-macosx_10_10_universal2.whl.metadata (4.0 kB)
Collecting tensorboard<2.14,>=2.13 (from tensorflow-macos==2.13.0->tensorflow)
  Downloading tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 16.9 MB/s eta 0:00:00a 0:00:01
Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for tensorflow-estimator<2.14,>=2.13.0 from https://files.pythonhosted.org/packages/72/5c/c318268d96791c6222ad7df1651bbd1b2409139afeb6f468c0f327177016/tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata
  Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras<2.14,>=2.13.1 (from tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for keras<2.14,>=2.13.1 from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata
  Downloading keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from astunparse>=1.6.0->tensorflow-macos==2.13.0->tensorflow) (0.38.4)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for google-auth<3,>=1.6.3 from https://files.pythonhosted.org/packages/9d/44/5a992cb9d7bf8aaae73bc5adaf721ad08731c9d00c1c17999a8691404b0c/google_auth-2.23.0-py2.py3-none-any.whl.metadata
  Downloading google_auth-2.23.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow)
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: markdown>=2.6.8 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (2.31.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for tensorboard-data-server<0.8.0,>=0.7.0 from https://files.pythonhosted.org/packages/da/61/6e9ff8258422d287eec718872fb71e05324356722ab658c8afda25f51539/tensorboard_data_server-0.7.1-py3-none-any.whl.metadata
  Downloading tensorboard_data_server-0.7.1-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (2.2.3)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow)
  Obtaining dependency information for cachetools<6.0,>=2.0.0 from https://files.pythonhosted.org/packages/a9/c9/c8a7710f2cedcb1db9224fdd4d8307c9e48cbddc46c18b515fefc0f1abbe/cachetools-5.3.1-py3-none-any.whl.metadata
  Downloading cachetools-5.3.1-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (0.2.8)
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow)

  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Requirement already satisfied: urllib3<2.0 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (1.26.16)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow)
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from requests<3,>=2.21.0->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from werkzeug>=1.0.1->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (2.1.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/nafilahamed/anaconda3/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow) (0.4.8)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow-macos==2.13.0->tensorflow)
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 11.2 MB/s eta 0:00:00
Downloading tensorflow-2.13.0-cp311-cp311-macosx_12_0_arm64.whl (1.9 kB)
Downloading tensorflow_macos-2.13.0-cp311-cp311-macosx_12_0_arm64.whl (189.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.3/189.3 MB 8.3 MB/s eta 0:00:00:00:0100:01
Downloading flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Downloading grpcio-1.58.0-cp311-cp311-macosx_10_10_universal2.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 10.5 MB/s eta 0:00:0000:0100:01
Downloading keras-2.13.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 11.4 MB/s eta 0:00:00a 0:00:01
Downloading libclang-16.0.6-py2.py3-none-macosx_11_0_arm64.whl (20.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 11.9 MB/s eta 0:00:0000:0100:01
Downloading protobuf-4.24.3-cp37-abi3-macosx_10_9_universal2.whl (409 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.4/409.4 kB 11.4 MB/s eta 0:00:00
Downloading tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 9.5 MB/s eta 0:00:00:00:01
Downloading google_auth-2.23.0-py2.py3-none-any.whl (181 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.4/181.4 kB 14.8 MB/s eta 0:00:00
Downloading tensorboard_data_server-0.7.1-py3-none-any.whl (2.4 kB)
Downloading cachetools-5.3.1-py3-none-any.whl (9.3 kB)
Installing collected packages: libclang, flatbuffers, typing-extensions, termcolor, tensorflow-estimator, tensorboard-data-server, rsa, protobuf, opt-einsum, oauthlib, keras, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow-macos, tensorflow
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: keras
    Found existing installation: keras 2.14.0
    Uninstalling keras-2.14.0:
      Successfully uninstalled keras-2.14.0
Successfully installed absl-py-1.4.0 astunparse-1.6.3 cachetools-5.3.1 flatbuffers-23.5.26 gast-0.4.0 google-auth-2.23.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.58.0 keras-2.13.1 libclang-16.0.6 oauthlib-3.2.2 opt-einsum-3.3.0 protobuf-4.24.3 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.13.0 tensorboard-data-server-0.7.1 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-macos-2.13.0 termcolor-2.3.0 typing-extensions-4.5.0

In [41]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import PReLU,LeakyReLU,ELU
from keras.layers import Dropout

In [47]:
classifier = Sequential()
classifier.add(Dense(units=6, kernel_initializer="he_uniform",activation= 'relu',input_dim=11))
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation= 'relu' ))
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))
classifier.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [51]:
model_history = classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
536/536 [==============================] - 1s 657us/step - loss: 0.5037 - accuracy: 0.7893 - val_loss: 0.4810 - val_accuracy: 0.7955
Epoch 2/100
536/536 [==============================] - 0s 504us/step - loss: 0.4630 - accuracy: 0.7972 - val_loss: 0.4593 - val_accuracy: 0.7967
Epoch 3/100
536/536 [==============================] - 0s 505us/step - loss: 0.4437 - accuracy: 0.8031 - val_loss: 0.4461 - val_accuracy: 0.8050
Epoch 4/100
536/536 [==============================] - 0s 501us/step - loss: 0.4306 - accuracy: 0.8108 - val_loss: 0.4359 - val_accuracy: 0.8099
Epoch 5/100
536/536 [==============================] - 0s 507us/step - loss: 0.4209 - accuracy: 0.8155 - val_loss: 0.4266 - val_accuracy: 0.8141
Epoch 6/100
536/536 [==============================] - 0s 505us/step - loss: 0.4115 - accuracy: 0.8207 - val_loss: 0.4203 - val_accuracy: 0.8141
Epoch 7/100
536/536 [==============================] - 0s 507us/step - loss: 0.4036 - accuracy: 0.8289 - val_loss: 0.4117 - val_accuracy: 0.8194
Epoch 8/100
536/536 [==============================] - 0s 515us/step - loss: 0.3941 - accuracy: 0.8373 - val_loss: 0.4028 - val_accuracy: 0.8251
Epoch 9/100
536/536 [==============================] - 0s 512us/step - loss: 0.3823 - accuracy: 0.8457 - val_loss: 0.3919 - val_accuracy: 0.8326
Epoch 10/100
536/536 [==============================] - 0s 512us/step - loss: 0.3691 - accuracy: 0.8517 - val_loss: 0.3785 - val_accuracy: 0.8387
Epoch 11/100
536/536 [==============================] - 0s 509us/step - loss: 0.3562 - accuracy: 0.8569 - val_loss: 0.3692 - val_accuracy: 0.8474
Epoch 12/100
536/536 [==============================] - 0s 535us/step - loss: 0.3472 - accuracy: 0.8591 - val_loss: 0.3632 - val_accuracy: 0.8493
Epoch 13/100
536/536 [==============================] - 0s 551us/step - loss: 0.3422 - accuracy: 0.8617 - val_loss: 0.3607 - val_accuracy: 0.8489
Epoch 14/100
536/536 [==============================] - 0s 530us/step - loss: 0.3394 - accuracy: 0.8591 - val_loss: 0.3599 - val_accuracy: 0.8485
Epoch 15/100
536/536 [==============================] - 0s 526us/step - loss: 0.3376 - accuracy: 0.8621 - val_loss: 0.3588 - val_accuracy: 0.8512
Epoch 16/100
536/536 [==============================] - 0s 528us/step - loss: 0.3369 - accuracy: 0.8606 - val_loss: 0.3578 - val_accuracy: 0.8523
Epoch 17/100
536/536 [==============================] - 0s 520us/step - loss: 0.3362 - accuracy: 0.8615 - val_loss: 0.3575 - val_accuracy: 0.8516
Epoch 18/100
536/536 [==============================] - 0s 504us/step - loss: 0.3353 - accuracy: 0.8612 - val_loss: 0.3571 - val_accuracy: 0.8535
Epoch 19/100
536/536 [==============================] - 0s 501us/step - loss: 0.3346 - accuracy: 0.8630 - val_loss: 0.3576 - val_accuracy: 0.8516
Epoch 20/100
536/536 [==============================] - 0s 503us/step - loss: 0.3348 - accuracy: 0.8606 - val_loss: 0.3591 - val_accuracy: 0.8527
Epoch 21/100
536/536 [==============================] - 0s 503us/step - loss: 0.3341 - accuracy: 0.8602 - val_loss: 0.3595 - val_accuracy: 0.8508
Epoch 22/100
536/536 [==============================] - 0s 511us/step - loss: 0.3339 - accuracy: 0.8597 - val_loss: 0.3564 - val_accuracy: 0.8523
Epoch 23/100
536/536 [==============================] - 0s 503us/step - loss: 0.3334 - accuracy: 0.8627 - val_loss: 0.3598 - val_accuracy: 0.8523
Epoch 24/100
536/536 [==============================] - 0s 506us/step - loss: 0.3339 - accuracy: 0.8595 - val_loss: 0.3557 - val_accuracy: 0.8542
Epoch 25/100
536/536 [==============================] - 0s 508us/step - loss: 0.3332 - accuracy: 0.8600 - val_loss: 0.3568 - val_accuracy: 0.8531
Epoch 26/100
536/536 [==============================] - 0s 505us/step - loss: 0.3331 - accuracy: 0.8625 - val_loss: 0.3567 - val_accuracy: 0.8542
Epoch 27/100
536/536 [==============================] - 0s 504us/step - loss: 0.3332 - accuracy: 0.8602 - val_loss: 0.3569 - val_accuracy: 0.8512
Epoch 28/100
536/536 [==============================] - 0s 513us/step - loss: 0.3326 - accuracy: 0.8614 - val_loss: 0.3578 - val_accuracy: 0.8516
Epoch 29/100
536/536 [==============================] - 0s 510us/step - loss: 0.3327 - accuracy: 0.8597 - val_loss: 0.3572 - val_accuracy: 0.8508
Epoch 30/100
536/536 [==============================] - 0s 549us/step - loss: 0.3323 - accuracy: 0.8615 - val_loss: 0.3580 - val_accuracy: 0.8512
Epoch 31/100
536/536 [==============================] - 0s 557us/step - loss: 0.3317 - accuracy: 0.8623 - val_loss: 0.3583 - val_accuracy: 0.8493
Epoch 32/100
536/536 [==============================] - 0s 541us/step - loss: 0.3320 - accuracy: 0.8619 - val_loss: 0.3572 - val_accuracy: 0.8474
Epoch 33/100
536/536 [==============================] - 0s 551us/step - loss: 0.3319 - accuracy: 0.8623 - val_loss: 0.3558 - val_accuracy: 0.8508
Epoch 34/100
536/536 [==============================] - 0s 535us/step - loss: 0.3316 - accuracy: 0.8617 - val_loss: 0.3553 - val_accuracy: 0.8535
Epoch 35/100
536/536 [==============================] - 0s 549us/step - loss: 0.3319 - accuracy: 0.8615 - val_loss: 0.3554 - val_accuracy: 0.8546
Epoch 36/100
536/536 [==============================] - 0s 540us/step - loss: 0.3314 - accuracy: 0.8647 - val_loss: 0.3553 - val_accuracy: 0.8542
Epoch 37/100
536/536 [==============================] - 0s 556us/step - loss: 0.3312 - accuracy: 0.8630 - val_loss: 0.3552 - val_accuracy: 0.8538
Epoch 38/100
536/536 [==============================] - 0s 541us/step - loss: 0.3311 - accuracy: 0.8636 - val_loss: 0.3542 - val_accuracy: 0.8519
Epoch 39/100
536/536 [==============================] - 0s 529us/step - loss: 0.3307 - accuracy: 0.8638 - val_loss: 0.3554 - val_accuracy: 0.8550
Epoch 40/100
536/536 [==============================] - 0s 517us/step - loss: 0.3306 - accuracy: 0.8630 - val_loss: 0.3554 - val_accuracy: 0.8516
Epoch 41/100
536/536 [==============================] - 0s 531us/step - loss: 0.3302 - accuracy: 0.8621 - val_loss: 0.3548 - val_accuracy: 0.8569
Epoch 42/100
536/536 [==============================] - 0s 527us/step - loss: 0.3305 - accuracy: 0.8634 - val_loss: 0.3547 - val_accuracy: 0.8527
Epoch 43/100
536/536 [==============================] - 0s 523us/step - loss: 0.3300 - accuracy: 0.8621 - val_loss: 0.3547 - val_accuracy: 0.8519
Epoch 44/100
536/536 [==============================] - 0s 525us/step - loss: 0.3301 - accuracy: 0.8630 - val_loss: 0.3566 - val_accuracy: 0.8508
Epoch 45/100
536/536 [==============================] - 0s 529us/step - loss: 0.3292 - accuracy: 0.8627 - val_loss: 0.3591 - val_accuracy: 0.8482
Epoch 46/100
536/536 [==============================] - 0s 519us/step - loss: 0.3303 - accuracy: 0.8628 - val_loss: 0.3569 - val_accuracy: 0.8523
Epoch 47/100
536/536 [==============================] - 0s 532us/step - loss: 0.3300 - accuracy: 0.8621 - val_loss: 0.3548 - val_accuracy: 0.8535
Epoch 48/100
536/536 [==============================] - 0s 515us/step - loss: 0.3293 - accuracy: 0.8617 - val_loss: 0.3553 - val_accuracy: 0.8516
Epoch 49/100
536/536 [==============================] - 0s 484us/step - loss: 0.3299 - accuracy: 0.8632 - val_loss: 0.3535 - val_accuracy: 0.8561
Epoch 50/100
536/536 [==============================] - 0s 560us/step - loss: 0.3294 - accuracy: 0.8634 - val_loss: 0.3544 - val_accuracy: 0.8527
Epoch 51/100
536/536 [==============================] - 0s 508us/step - loss: 0.3294 - accuracy: 0.8619 - val_loss: 0.3535 - val_accuracy: 0.8561
Epoch 52/100
536/536 [==============================] - 0s 509us/step - loss: 0.3288 - accuracy: 0.8634 - val_loss: 0.3545 - val_accuracy: 0.8527
Epoch 53/100
536/536 [==============================] - 0s 510us/step - loss: 0.3290 - accuracy: 0.8630 - val_loss: 0.3534 - val_accuracy: 0.8535
Epoch 54/100
536/536 [==============================] - 0s 512us/step - loss: 0.3292 - accuracy: 0.8614 - val_loss: 0.3543 - val_accuracy: 0.8531
Epoch 55/100
536/536 [==============================] - 0s 506us/step - loss: 0.3289 - accuracy: 0.8628 - val_loss: 0.3528 - val_accuracy: 0.8588
Epoch 56/100
536/536 [==============================] - 0s 509us/step - loss: 0.3291 - accuracy: 0.8640 - val_loss: 0.3540 - val_accuracy: 0.8538
Epoch 57/100

536/536 [==============================] - 0s 504us/step - loss: 0.3286 - accuracy: 0.8638 - val_loss: 0.3532 - val_accuracy: 0.8554
Epoch 58/100
536/536 [==============================] - 0s 505us/step - loss: 0.3294 - accuracy: 0.8628 - val_loss: 0.3526 - val_accuracy: 0.8565
Epoch 59/100
536/536 [==============================] - 0s 507us/step - loss: 0.3289 - accuracy: 0.8642 - val_loss: 0.3545 - val_accuracy: 0.8546
Epoch 60/100
536/536 [==============================] - 0s 504us/step - loss: 0.3288 - accuracy: 0.8636 - val_loss: 0.3548 - val_accuracy: 0.8550
Epoch 61/100
536/536 [==============================] - 0s 503us/step - loss: 0.3286 - accuracy: 0.8615 - val_loss: 0.3531 - val_accuracy: 0.8565
Epoch 62/100
536/536 [==============================] - 0s 504us/step - loss: 0.3287 - accuracy: 0.8632 - val_loss: 0.3533 - val_accuracy: 0.8557
Epoch 63/100
536/536 [==============================] - 0s 504us/step - loss: 0.3288 - accuracy: 0.8627 - val_loss: 0.3524 - val_accuracy: 0.8565
Epoch 64/100
536/536 [==============================] - 0s 504us/step - loss: 0.3275 - accuracy: 0.8670 - val_loss: 0.3532 - val_accuracy: 0.8550
Epoch 65/100
536/536 [==============================] - 0s 500us/step - loss: 0.3286 - accuracy: 0.8632 - val_loss: 0.3531 - val_accuracy: 0.8546
Epoch 66/100
536/536 [==============================] - 0s 504us/step - loss: 0.3284 - accuracy: 0.8636 - val_loss: 0.3538 - val_accuracy: 0.8550
Epoch 67/100
536/536 [==============================] - 0s 506us/step - loss: 0.3280 - accuracy: 0.8640 - val_loss: 0.3542 - val_accuracy: 0.8527
Epoch 68/100
536/536 [==============================] - 0s 503us/step - loss: 0.3284 - accuracy: 0.8651 - val_loss: 0.3528 - val_accuracy: 0.8538
Epoch 69/100
536/536 [==============================] - 0s 509us/step - loss: 0.3285 - accuracy: 0.8638 - val_loss: 0.3524 - val_accuracy: 0.8565
Epoch 70/100
536/536 [==============================] - 0s 509us/step - loss: 0.3284 - accuracy: 0.8649 - val_loss: 0.3523 - val_accuracy: 0.8565
Epoch 71/100
536/536 [==============================] - 0s 507us/step - loss: 0.3285 - accuracy: 0.8642 - val_loss: 0.3529 - val_accuracy: 0.8538
Epoch 72/100
536/536 [==============================] - 0s 503us/step - loss: 0.3285 - accuracy: 0.8615 - val_loss: 0.3530 - val_accuracy: 0.8546
Epoch 73/100
536/536 [==============================] - 0s 515us/step - loss: 0.3276 - accuracy: 0.8640 - val_loss: 0.3547 - val_accuracy: 0.8531
Epoch 74/100
536/536 [==============================] - 0s 502us/step - loss: 0.3277 - accuracy: 0.8638 - val_loss: 0.3527 - val_accuracy: 0.8546
Epoch 75/100
536/536 [==============================] - 0s 506us/step - loss: 0.3281 - accuracy: 0.8642 - val_loss: 0.3519 - val_accuracy: 0.8538
Epoch 76/100
536/536 [==============================] - 0s 507us/step - loss: 0.3281 - accuracy: 0.8630 - val_loss: 0.3529 - val_accuracy: 0.8546
Epoch 77/100
536/536 [==============================] - 0s 508us/step - loss: 0.3279 - accuracy: 0.8649 - val_loss: 0.3518 - val_accuracy: 0.8565
Epoch 78/100
536/536 [==============================] - 0s 505us/step - loss: 0.3281 - accuracy: 0.8645 - val_loss: 0.3524 - val_accuracy: 0.8538
Epoch 79/100
536/536 [==============================] - 0s 512us/step - loss: 0.3277 - accuracy: 0.8643 - val_loss: 0.3520 - val_accuracy: 0.8538
Epoch 80/100
536/536 [==============================] - 0s 529us/step - loss: 0.3277 - accuracy: 0.8653 - val_loss: 0.3523 - val_accuracy: 0.8542
Epoch 81/100
536/536 [==============================] - 0s 525us/step - loss: 0.3271 - accuracy: 0.8645 - val_loss: 0.3521 - val_accuracy: 0.8573
Epoch 82/100
536/536 [==============================] - 0s 526us/step - loss: 0.3274 - accuracy: 0.8636 - val_loss: 0.3520 - val_accuracy: 0.8557
Epoch 83/100
536/536 [==============================] - 0s 525us/step - loss: 0.3272 - accuracy: 0.8636 - val_loss: 0.3513 - val_accuracy: 0.8569
Epoch 84/100
536/536 [==============================] - 0s 517us/step - loss: 0.3272 - accuracy: 0.8634 - val_loss: 0.3529 - val_accuracy: 0.8550
Epoch 85/100
536/536 [==============================] - 0s 511us/step - loss: 0.3272 - accuracy: 0.8640 - val_loss: 0.3545 - val_accuracy: 0.8538
Epoch 86/100
536/536 [==============================] - 0s 507us/step - loss: 0.3270 - accuracy: 0.8619 - val_loss: 0.3523 - val_accuracy: 0.8554
Epoch 87/100
536/536 [==============================] - 0s 508us/step - loss: 0.3271 - accuracy: 0.8647 - val_loss: 0.3530 - val_accuracy: 0.8550
Epoch 88/100
536/536 [==============================] - 0s 508us/step - loss: 0.3267 - accuracy: 0.8643 - val_loss: 0.3532 - val_accuracy: 0.8546
Epoch 89/100
536/536 [==============================] - 0s 521us/step - loss: 0.3275 - accuracy: 0.8658 - val_loss: 0.3508 - val_accuracy: 0.8573
Epoch 90/100
536/536 [==============================] - 0s 522us/step - loss: 0.3267 - accuracy: 0.8634 - val_loss: 0.3513 - val_accuracy: 0.8561
Epoch 91/100
536/536 [==============================] - 0s 517us/step - loss: 0.3264 - accuracy: 0.8660 - val_loss: 0.3520 - val_accuracy: 0.8542
Epoch 92/100
536/536 [==============================] - 0s 516us/step - loss: 0.3268 - accuracy: 0.8651 - val_loss: 0.3512 - val_accuracy: 0.8576
Epoch 93/100
536/536 [==============================] - 0s 505us/step - loss: 0.3270 - accuracy: 0.8649 - val_loss: 0.3523 - val_accuracy: 0.8576
Epoch 94/100
536/536 [==============================] - 0s 509us/step - loss: 0.3263 - accuracy: 0.8640 - val_loss: 0.3514 - val_accuracy: 0.8565
Epoch 95/100
536/536 [==============================] - 0s 501us/step - loss: 0.3265 - accuracy: 0.8662 - val_loss: 0.3550 - val_accuracy: 0.8542
Epoch 96/100
536/536 [==============================] - 0s 510us/step - loss: 0.3270 - accuracy: 0.8662 - val_loss: 0.3522 - val_accuracy: 0.8554
Epoch 97/100
536/536 [==============================] - 0s 505us/step - loss: 0.3263 - accuracy: 0.8656 - val_loss: 0.3527 - val_accuracy: 0.8546
Epoch 98/100
536/536 [==============================] - 0s 501us/step - loss: 0.3269 - accuracy: 0.8643 - val_loss: 0.3513 - val_accuracy: 0.8576
Epoch 99/100
536/536 [==============================] - 0s 506us/step - loss: 0.3264 - accuracy: 0.8651 - val_loss: 0.3524 - val_accuracy: 0.8535
Epoch 100/100
536/536 [==============================] - 0s 507us/step - loss: 0.3264 - accuracy: 0.8651 - val_loss: 0.3516 - val_accuracy: 0.8542

In [53]:
y_predict = classifier.predict(X_test)
y_predict = (y_predict>0.5)
y_predict

63/63 [==============================] - 0s 348us/step

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [54]:
from sklearn.metrics import accuracy_score
score= accuracy_score(y_predict,y_test)

In [55]:
score

0.862

In [58]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_predict)
cm

array([[1524,   71],
       [ 205,  200]])